apiRules:
- include:
    # Including the OmiyaGames.Managers namespace
    uidRegex: ^OmiyaGames\.Managers$
    type: Namespace
- include:
    # Including the OmiyaGames.Managers.Editor namespace
    uidRegex: ^OmiyaGames\.Managers\.Editor$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    # Taro Omiya: note that I'm ignoring namespaces containing unit tests on purpooses
    uidRegex: .*
    type: Namespace
